[build]
command = "yarn rw build && yarn prisma migrate deploy --preview-feature --schema=api/db/schema.prisma && yarn rw dataMigrate up"
publish = "web/dist"
functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
